using System.Text;
using System.Text.RegularExpressions;

namespace Kronikol.Reports.SearchIndex;

/// <summary>
/// The SEARCH_INDEX_PLAN §4.1 shared normalization, C# side. Users search for what they see
/// rendered, so both the generation-time index and the client verify pass normalize identically;
/// this implementation is pinned byte-for-byte to the shipped report JS by the shared vectors in
/// tests/shared-vectors/search-index-vectors.json (generated by tools/search-bench/gen-vectors.js
/// from the reference implementation tools/search-bench/normalize.js).
/// </summary>
internal static partial class SearchNormalizer
{
    // 3. Creole escape ~ before the characters the formatter escapes (same set the context-menu
    //    copy-text inverse strips: / * _ - " [ < # =).
    [GeneratedRegex("~(?=[/*_\\-\"\\[<#=])")]
    private static partial Regex CreoleEscapeRegex();

    // 4. PlantUML inline markup tags.
    [GeneratedRegex("</?(?:color|font|i|b|size|back)[^>]*>")]
    private static partial Regex MarkupTagRegex();

    // 5a. Arrow-label literal \n escape sequence plus trailing indent.
    [GeneratedRegex(@"\\n[ \t]*")]
    private static partial Regex ArrowLabelBreakRegex();

    // 6. Collapse space/tab runs.
    [GeneratedRegex("[ \t]+")]
    private static partial Regex WhitespaceRunRegex();

    internal static string Normalize(string text)
    {
        // 1. canonicalize CRLF
        var s = text.Replace("\r\n", "\n");

        // 2. ASCII-only case fold (NOT ToLowerInvariant: İ/ß/combining marks must be untouched
        //    so C# and JS agree — measured divergence otherwise, see plan §4.1 rule 2)
        s = AsciiFold(s);

        s = CreoleEscapeRegex().Replace(s, "");
        s = MarkupTagRegex().Replace(s, "");
        s = ArrowLabelBreakRegex().Replace(s, "");

        // 5b. note-body rejoin: delete a newline whose next line starts flush-left with a
        //     non-whitespace character, scoped to note bodies (chunking and run wrapping only
        //     apply there; re-indented JSON lines keep their structural newlines).
        var sb = new StringBuilder(s.Length + 1);
        var inNote = false;
        var first = true;
        foreach (var line in s.Split('\n'))
        {
            var trimmed = line.Trim();
            if (trimmed.StartsWith("note left", StringComparison.Ordinal)
                || trimmed.StartsWith("note right", StringComparison.Ordinal)
                || trimmed.StartsWith("note over", StringComparison.Ordinal))
            {
                inNote = true;
                if (!first) sb.Append('\n');
                sb.Append(line);
            }
            else if (trimmed == "end note")
            {
                inNote = false;
                if (!first) sb.Append('\n');
                sb.Append(line);
            }
            else if (inNote && !first && line.Length > 0 && !char.IsWhiteSpace(line[0]))
            {
                sb.Append(line); // rejoin flush-left continuation
            }
            else
            {
                if (!first) sb.Append('\n');
                sb.Append(line);
            }
            first = false;
        }
        sb.Append('\n');

        return WhitespaceRunRegex().Replace(sb.ToString(), " ");
    }

    private static string AsciiFold(string s)
    {
        var chars = s.ToCharArray();
        for (var i = 0; i < chars.Length; i++)
        {
            var c = chars[i];
            if (c is >= 'A' and <= 'Z') chars[i] = (char)(c + 32);
        }
        return new string(chars);
    }
}
