using System.Text;

namespace Kronikol.Reports.SearchIndex;

/// <summary>
/// The SEARCH_INDEX_PLAN §4.1 shared normalization, C# side. Users search for what they see
/// rendered, so both the generation-time index and the client verify pass normalize identically;
/// this implementation is pinned byte-for-byte to the shipped report JS by the shared vectors in
/// tests/shared-vectors/search-index-vectors.json (generated by tools/search-bench/gen-vectors.js
/// from the reference implementation tools/search-bench/normalize.js).
/// <para>
/// Implemented as hand-rolled scans rather than the reference's regex passes: normalization runs
/// over the full diagram corpus (100MB-class on monster reports) inside report generation, and
/// the regex version measured as the dominant index-build cost (M3). Equivalence with the regex
/// semantics is pinned by <c>SearchNormalizerEquivalenceTests</c> in addition to the vectors.
/// </para>
/// </summary>
internal static class SearchNormalizer
{
    internal static string Normalize(string text)
    {
        // The passes run in the reference's exact order and separately — deletions in one pass
        // can enable matches in the next (e.g. a stripped tag merges two space runs that 5a then
        // consumes together; a stripped creole ~ can complete a `</` tag opener), so fusing them
        // into one scan diverges. Each pass is a plain O(n) scan; only the ORDER is semantic.
        //
        // Rule 5b used to sit at the end: any note-body line that did not start with whitespace was
        // welded to the line above, on the assumption that a flush-left continuation could only be a
        // wrap. Right for indented JSON, wrong for a plain-text or SQL payload whose real lines start
        // at column 0 — and unnecessary now that the generator marks the breaks it inserts.
        // Rule 1b runs first, before the fold and before rule 3, because rule 3 strips the `~` that
        // tells Kronikol's own join marker from a payload that literally contains "<U+200B>". It
        // calls the generator's implementation rather than restating it — the two JS copies exist
        // only because they cannot reach this one, and the shared vectors pin all three together.
        var s = PlantUml.DiagramWidth.RejoinMarkedLines(text.Replace("\r\n", "\n"));  // rules 1 + 1b
        s = FoldAndCanonicalize(s);          // rule 2 (rule 1 is already applied)
        s = StripCreoleEscapes(s);           // rule 3
        s = StripMarkupTags(s);              // rule 4
        s = StripArrowLabelBreaks(s);        // rule 5a
        return CollapseSpaces(s + "\n");     // rule 6
    }

    // Creole escape targets: the same set the formatter escapes and the context-menu inverse strips.
    private static bool IsCreoleEscapable(char c) =>
        c is '/' or '*' or '_' or '-' or '"' or '[' or '<' or '#' or '=';

    private static readonly string[] TagPrefixes = ["color", "font", "i", "b", "size", "back"];

    /// <summary>
    /// Matches the reference regex <c>&lt;/?(?:color|font|i|b|size|back)[^&gt;]*&gt;</c> at
    /// <paramref name="start"/> (which holds '&lt;'). The input is already ASCII-folded, so the
    /// prefixes compare lowercase-to-lowercase.
    /// </summary>
    private static bool TryMatchTag(string s, int start, out int end)
    {
        end = 0;
        var j = start + 1;
        if (j < s.Length && s[j] == '/') j++;
        var matched = false;
        foreach (var prefix in TagPrefixes)
        {
            if (j + prefix.Length > s.Length) continue;
            if (s.AsSpan(j, prefix.Length).SequenceEqual(prefix)) { matched = true; break; }
        }
        if (!matched) return false;
        var gt = s.IndexOf('>', j);
        if (gt < 0) return false;
        end = gt + 1;
        return true;
    }

    private static string FoldAndCanonicalize(string text)
    {
        var n = text.Length;
        var sb = new StringBuilder(n);
        for (var i = 0; i < n; i++)
        {
            var c = text[i];
            if (c == '\r' && i + 1 < n && text[i + 1] == '\n') continue; // drop the \r of CRLF
            if (c is >= 'A' and <= 'Z') c = (char)(c + 32);
            sb.Append(c);
        }
        return sb.ToString();
    }

    private static string StripCreoleEscapes(string s)
    {
        if (s.IndexOf('~') < 0) return s;
        var n = s.Length;
        var sb = new StringBuilder(n);
        for (var i = 0; i < n; i++)
        {
            if (s[i] == '~' && i + 1 < n && IsCreoleEscapable(s[i + 1])) continue;
            sb.Append(s[i]);
        }
        return sb.ToString();
    }

    private static string StripMarkupTags(string s)
    {
        if (s.IndexOf('<') < 0) return s;
        var n = s.Length;
        var sb = new StringBuilder(n);
        var i = 0;
        while (i < n)
        {
            if (s[i] == '<' && TryMatchTag(s, i, out var tagEnd)) { i = tagEnd; continue; }
            sb.Append(s[i]);
            i++;
        }
        return sb.ToString();
    }

    private static string StripArrowLabelBreaks(string s)
    {
        if (s.IndexOf('\\') < 0) return s;
        var n = s.Length;
        var sb = new StringBuilder(n);
        var i = 0;
        while (i < n)
        {
            if (s[i] == '\\' && i + 1 < n && s[i + 1] == 'n')
            {
                i += 2;
                while (i < n && (s[i] == ' ' || s[i] == '\t')) i++;
                continue;
            }
            sb.Append(s[i]);
            i++;
        }
        return sb.ToString();
    }


    private static string CollapseSpaces(string s)
    {
        var n = s.Length;
        var sb = new StringBuilder(n);
        var i = 0;
        while (i < n)
        {
            var c = s[i];
            if (c == ' ' || c == '\t')
            {
                sb.Append(' ');
                while (i < n && (s[i] == ' ' || s[i] == '\t')) i++;
                continue;
            }
            sb.Append(c);
            i++;
        }
        return sb.ToString();
    }
}
