using System.Text;

namespace Kronikol.Reports.SearchIndex;

/// <summary>
/// The SEARCH_INDEX_PLAN §4.1 shared normalization, C# side. Users search for what they see
/// rendered, so both the generation-time index and the client verify pass normalize identically;
/// this implementation is pinned byte-for-byte to the shipped report JS by the shared vectors in
/// tests/shared-vectors/search-index-vectors.json (generated by tools/search-bench/gen-vectors.js
/// from the reference implementation tools/search-bench/normalize.js).
/// <para>
/// Implemented as hand-rolled scans rather than the reference's regex passes: normalization runs
/// over the full diagram corpus (100MB-class on monster reports) inside report generation, and
/// the regex version measured as the dominant index-build cost (M3). Equivalence with the regex
/// semantics is pinned by <c>SearchNormalizerEquivalenceTests</c> in addition to the vectors.
/// </para>
/// </summary>
internal static class SearchNormalizer
{
    internal static string Normalize(string text)
    {
        // The passes run in the reference's exact order and separately — deletions in one pass
        // can enable matches in the next (e.g. a stripped tag merges two space runs that 5a then
        // consumes together; a stripped creole ~ can complete a `</` tag opener), so fusing them
        // into one scan diverges. Each pass is a plain O(n) scan; only the ORDER is semantic.
        var s = FoldAndCanonicalize(text);   // rules 1 (CRLF) + 2 (ASCII fold)
        s = StripCreoleEscapes(s);           // rule 3
        s = StripMarkupTags(s);              // rule 4
        s = StripArrowLabelBreaks(s);        // rule 5a
        s = RejoinNoteBodies(s);             // rule 5b
        return CollapseSpaces(s);            // rule 6
    }

    // Creole escape targets: the same set the formatter escapes and the context-menu inverse strips.
    private static bool IsCreoleEscapable(char c) =>
        c is '/' or '*' or '_' or '-' or '"' or '[' or '<' or '#' or '=';

    private static readonly string[] TagPrefixes = ["color", "font", "i", "b", "size", "back"];

    /// <summary>
    /// Matches the reference regex <c>&lt;/?(?:color|font|i|b|size|back)[^&gt;]*&gt;</c> at
    /// <paramref name="start"/> (which holds '&lt;'). The input is already ASCII-folded, so the
    /// prefixes compare lowercase-to-lowercase.
    /// </summary>
    private static bool TryMatchTag(string s, int start, out int end)
    {
        end = 0;
        var j = start + 1;
        if (j < s.Length && s[j] == '/') j++;
        var matched = false;
        foreach (var prefix in TagPrefixes)
        {
            if (j + prefix.Length > s.Length) continue;
            if (s.AsSpan(j, prefix.Length).SequenceEqual(prefix)) { matched = true; break; }
        }
        if (!matched) return false;
        var gt = s.IndexOf('>', j);
        if (gt < 0) return false;
        end = gt + 1;
        return true;
    }

    private static string FoldAndCanonicalize(string text)
    {
        var n = text.Length;
        var sb = new StringBuilder(n);
        for (var i = 0; i < n; i++)
        {
            var c = text[i];
            if (c == '\r' && i + 1 < n && text[i + 1] == '\n') continue; // drop the \r of CRLF
            if (c is >= 'A' and <= 'Z') c = (char)(c + 32);
            sb.Append(c);
        }
        return sb.ToString();
    }

    private static string StripCreoleEscapes(string s)
    {
        if (s.IndexOf('~') < 0) return s;
        var n = s.Length;
        var sb = new StringBuilder(n);
        for (var i = 0; i < n; i++)
        {
            if (s[i] == '~' && i + 1 < n && IsCreoleEscapable(s[i + 1])) continue;
            sb.Append(s[i]);
        }
        return sb.ToString();
    }

    private static string StripMarkupTags(string s)
    {
        if (s.IndexOf('<') < 0) return s;
        var n = s.Length;
        var sb = new StringBuilder(n);
        var i = 0;
        while (i < n)
        {
            if (s[i] == '<' && TryMatchTag(s, i, out var tagEnd)) { i = tagEnd; continue; }
            sb.Append(s[i]);
            i++;
        }
        return sb.ToString();
    }

    private static string StripArrowLabelBreaks(string s)
    {
        if (s.IndexOf('\\') < 0) return s;
        var n = s.Length;
        var sb = new StringBuilder(n);
        var i = 0;
        while (i < n)
        {
            if (s[i] == '\\' && i + 1 < n && s[i + 1] == 'n')
            {
                i += 2;
                while (i < n && (s[i] == ' ' || s[i] == '\t')) i++;
                continue;
            }
            sb.Append(s[i]);
            i++;
        }
        return sb.ToString();
    }

    /// <summary>
    /// The JS <c>/\s/</c> character class, exactly — NOT <see cref="char.IsWhiteSpace(char)"/>.
    /// The two disagree on U+0085 (NEL: .NET whitespace, JS not) and U+FEFF (JS whitespace,
    /// .NET not); rule 5b's flush-left test and trims must match the client verify byte-for-byte
    /// or the index and the verify corpus diverge on those characters (a deep false negative).
    /// </summary>
    private static bool IsJsWhitespace(char c) =>
        c is ' ' or '\t' or '\n' or '\v' or '\f' or '\r' or '\u00a0' or '\u1680'
          or (>= '\u2000' and <= '\u200a') or '\u2028' or '\u2029' or '\u202f' or '\u205f' or '\u3000' or '\ufeff';

    private static ReadOnlySpan<char> JsTrim(ReadOnlySpan<char> line)
    {
        var start = 0;
        var end = line.Length;
        while (start < end && IsJsWhitespace(line[start])) start++;
        while (end > start && IsJsWhitespace(line[end - 1])) end--;
        return line[start..end];
    }

    private static bool IsWordChar(char c) => c is (>= 'a' and <= 'z') or (>= 'A' and <= 'Z') or (>= '0' and <= '9') or '_';

    private static readonly string[] NoteSides = ["left", "right", "over", "across"];

    /// <summary>
    /// Matches the reference regex <c>/^[hr]?note(?:&lt;&lt;[^&gt;]*&gt;&gt;)? (left|right|over|across)\b/</c>
    /// plus its no-<c>:</c> guard: every multi-line note form the formatter emits (`note left`,
    /// `note&lt;&lt;class&gt;&gt; right` event notes, `hnote across &lt;&lt;class&gt;&gt;` assertion/render-error
    /// notes). A colon anywhere on the directive line marks PlantUML's single-line note form
    /// (step delimiters, row markers) — no body follows, so it must not enter note mode.
    /// </summary>
    private static bool IsNoteOpener(ReadOnlySpan<char> trimmed)
    {
        if (trimmed.IndexOf(':') >= 0) return false;
        var i = 0;
        if (i < trimmed.Length && (trimmed[i] == 'h' || trimmed[i] == 'r')) i++;
        if (!trimmed[i..].StartsWith("note")) return false;
        i += 4;
        if (i + 1 < trimmed.Length && trimmed[i] == '<' && trimmed[i + 1] == '<')
        {
            var j = i + 2;
            while (j < trimmed.Length && trimmed[j] != '>') j++;      // [^>]*
            if (j + 1 >= trimmed.Length || trimmed[j + 1] != '>') return false;
            i = j + 2;
        }
        if (i >= trimmed.Length || trimmed[i] != ' ') return false;
        i++;
        foreach (var side in NoteSides)
        {
            if (!trimmed[i..].StartsWith(side)) continue;
            var after = i + side.Length;
            return after >= trimmed.Length || !IsWordChar(trimmed[after]); // \b
        }
        return false;
    }

    private static string RejoinNoteBodies(string s)
    {
        var sb = new StringBuilder(s.Length + 1);
        var inNote = false;
        var first = true;
        var pos = 0;
        while (true)
        {
            var nl = s.IndexOf('\n', pos);
            var end = nl < 0 ? s.Length : nl;
            var line = s.AsSpan(pos, end - pos);
            var trimmed = JsTrim(line);
            if (IsNoteOpener(trimmed))
            {
                inNote = true;
                if (!first) sb.Append('\n');
                sb.Append(line);
            }
            else if (trimmed.SequenceEqual("end note"))
            {
                inNote = false;
                if (!first) sb.Append('\n');
                sb.Append(line);
            }
            else if (inNote && !first && line.Length > 0 && !IsJsWhitespace(line[0]))
            {
                sb.Append(line); // rejoin flush-left continuation
            }
            else
            {
                if (!first) sb.Append('\n');
                sb.Append(line);
            }
            first = false;
            if (nl < 0) break;
            pos = nl + 1;
        }
        sb.Append('\n');
        return sb.ToString();
    }

    private static string CollapseSpaces(string s)
    {
        var n = s.Length;
        var sb = new StringBuilder(n);
        var i = 0;
        while (i < n)
        {
            var c = s[i];
            if (c == ' ' || c == '\t')
            {
                sb.Append(' ');
                while (i < n && (s[i] == ' ' || s[i] == '\t')) i++;
                continue;
            }
            sb.Append(c);
            i++;
        }
        return sb.ToString();
    }
}
