@startuml
!pragma teoz true


skinparam wrapWidth 800
autonumber 1

actor "Caller" as caller
entity "Orders API" as ordersAPI

caller -[#438DD5]> ordersAPI: POST: /api/orders
note left
<color:gray>[Content-Type=application/json]

{
  "sku": "A1"
}
end note
ordersAPI -[#438DD5]-> caller: Bad Request
note right
<color:gray>[Content-Type=application/json]

{
  "error": "expected Vec<&str>, found String"
}
end note
@enduml
