<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <AssemblyName>history-replay</AssemblyName>
    <RootNamespace>HistoryReplay</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Kronikol\Kronikol.csproj" />
  </ItemGroup>

</Project>
