// Generates the §9.1 shared test vectors (tests/shared-vectors/search-index-vectors.json) from
// the reference implementations: normalize.js (§4.1) + the FNV-1a trigram hash + the §4.2 v1
// serialization. The C# unit tests and the Jint tests over the shipped report JS both assert
// against this file — it is the cross-language pin (and the Kronikol4J porting spec).
'use strict';
const fs = require('fs');
const path = require('path');
const { normalizeForSearch } = require('./normalize');

const FNV_OFF = 0x811c9dc5, FNV_PRIME = 0x01000193;
function trigramBuckets(s, B) {
  const set = new Set();
  for (let i = 0, n = s.length - 2; i < n; i++) {
    let h = FNV_OFF;
    h = Math.imul(h ^ s.charCodeAt(i), FNV_PRIME);
    h = Math.imul(h ^ s.charCodeAt(i + 1), FNV_PRIME);
    h = Math.imul(h ^ s.charCodeAt(i + 2), FNV_PRIME);
    set.add((h >>> 0) & (B - 1));
  }
  return [...set].sort((a, b) => a - b);
}

// §4.2 v1 layout: magic KSI1 | u8 version | u32le B | u32le docCount |
// doc table: docCount x (varint byteLen + UTF-8) |
// rows: B x (varint payloadLen; 0 = empty; else payload = u8 encoding + body)
//   encoding 1 = bitset body ceil(D/8) bytes; encoding 2 = varint count + doc ids as
//   varints (first absolute, rest delta from previous). Smaller body wins.
function varint(v) {
  const out = [];
  while (v >= 128) { out.push((v & 127) | 128); v >>>= 7; }
  out.push(v);
  return out;
}
function serialize(docAnchors, bucketsPerDoc, B) {
  const D = docAnchors.length, bitsetBytes = (D + 7) >> 3;
  const rows = new Map(); // bucket -> [docIds]
  bucketsPerDoc.forEach((buckets, d) => buckets.forEach(b => {
    if (!rows.has(b)) rows.set(b, []);
    rows.get(b).push(d);
  }));
  const bytes = [0x4b, 0x53, 0x49, 0x31, 1]; // 'KSI1', version 1
  const pushU32 = v => bytes.push(v & 255, (v >> 8) & 255, (v >> 16) & 255, (v >>> 24) & 255);
  pushU32(B); pushU32(D);
  for (const a of docAnchors) {
    const utf8 = Buffer.from(a, 'utf8');
    bytes.push(...varint(utf8.length), ...utf8);
  }
  for (let b = 0; b < B; b++) {
    const r = rows.get(b);
    if (!r) { bytes.push(0); continue; }
    const list = [];
    let prev = 0;
    r.forEach((d, i) => { list.push(...varint(i === 0 ? d : d - prev)); prev = d; });
    const listBody = [...varint(r.length), ...list];
    if (listBody.length < bitsetBytes) {
      bytes.push(...varint(1 + listBody.length), 2, ...listBody);
    } else {
      const bs = new Array(bitsetBytes).fill(0);
      for (const d of r) bs[d >> 3] |= 1 << (d & 7);
      bytes.push(...varint(1 + bitsetBytes), 1, ...bs);
    }
  }
  return Buffer.from(bytes);
}

const normalizationInputs = [
  ['crlf', 'first line\r\nsecond line'],
  ['ascii-fold-basic', 'Hello WORLD MixedCase'],
  ['ascii-fold-leaves-nonascii', 'İstanbul ẞß ÅÄÖ café'],
  ['combining-marks-untouched', 'éclair å'],
  ['creole-escapes', 'x ~*~*important~*~* and ~/~/slanted~/~/ plus ~_~_deep~_~_ ~[link~] ~"q~" ~-dash'],
  ['creole-line-leading-escapes', '~# heading-like payload line\n~= another\n~* bullet-like'],
  ['markup-tags', '<color:gray>[Content-Type=application/json]</color> <font color="red">x</font> <i>[binary content]</i> <b>bold</b>'],
  ['arrow-label-5a', 'test -> svc: POST: /orders/pppp\\n        qqqq more'],
  ['note-chunk-rejoin-5b', 'note left\n<color:gray>[X-H=aaaaaaaa\n<color:gray>bbbbbbbb]\n\n{\n  "blob": "AAAA\nBBBB",\n  "ok": true\n}\nend note'],
  ['note-boundary-survives', 'note right\npayload\nend note\nafter -> b: hi'],
  ['whitespace-collapse', 'a  b\tc   d'],
  ['plain-multiline-outside-note-kept', 'alpha\nbeta\ngamma'],
  ['empty', ''],
];

const trigramInputs = ['abc', 'abcd', 'needle', 'order id', 'İs', 'aaa'];

const B = 65536;
const serializationCase = {
  buckets: B,
  docAnchors: ['create-order', 'create-order-2', 'withdraw-cash'],
  bucketsPerDoc: [
    trigramBuckets('the first document body', B),
    trigramBuckets('the second document body', B),
    trigramBuckets('a third thing entirely', B),
  ],
};
serializationCase.rawBase64 = serialize(
  serializationCase.docAnchors, serializationCase.bucketsPerDoc, B).toString('base64');

const vectors = {
  comment: 'GENERATED by tools/search-bench/gen-vectors.js — do not hand-edit. Cross-language pin for SEARCH_INDEX_PLAN §4.1/§4.2 (C# generation, shipped report JS, Kronikol4J).',
  fnv: { offset: 0x811c9dc5, prime: 0x01000193 },
  normalization: normalizationInputs.map(([name, input]) => ({ name, input, expected: normalizeForSearch(input) })),
  trigrams: trigramInputs.map(text => ({ text, buckets65536: trigramBuckets(text, B) })),
  serialization: serializationCase,
};

const outPath = path.join(__dirname, '..', '..', 'tests', 'shared-vectors', 'search-index-vectors.json');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, JSON.stringify(vectors, null, 2));
console.log('wrote ' + outPath);
