"""Writes results/SUMMARY.md from the files run.ps1 and perf.ps1 saved under results/.

Every fact in it is read from a file under results/ and names that file, so the summary can be regenerated
and checked: python tools/summarize.py results
"""
import json
import pathlib
import re
import statistics
import sys

RESULTS = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else pathlib.Path(__file__).resolve().parent.parent / "results")

NEVER_BEFORE = {
    "Probe.Facts.Skipped": "[Fact(Skip)]",
    "Probe.CtorThrows.Never_runs": "constructor throws",
    "Probe.InitThrows.Never_runs": "InitializeAsync throws",
    "Probe.FixtureThrows.Never_runs": "class fixture throws",
}
DISPLAY = ["A failing fact with a display name", "A passing fact with a display name"]
DOTS = ["Order API returns 404 for v1.2", "Does the thing."]
LANE_ORDER = [
    "A.OwnFramework", "A.OwnFramework-runner3.1.5", "A2.MethodDisplay", "A3.StartTimeProbe", "B.AssemblyFixtureOnly",
    "C.AssemblyFixturePrototype-sync1", "C.AssemblyFixturePrototype-sync0",
    "C.AssemblyFixturePrototype-sync1-unguarded", "C.AssemblyFixturePrototype-sync0-unguarded", "E.CollectionFixtureOnly",
    "F.DependencyInjectionPrototype-sync1", "F.DependencyInjectionPrototype-sync0",
]
LANE_TEXT = {
    "A.OwnFramework": "Kronikol.xUnit2's ReportingTestFramework, runner 2.8.2 (today's baseline)",
    "A.OwnFramework-runner3.1.5": "A built against xunit.runner.visualstudio 3.1.5",
    "A2.MethodDisplay": "A with xunit.runner.json {\"methodDisplay\": \"method\"}",
    "A3.StartTimeProbe": "A plus a ProcessExit hook that reads ReportLifecycle.StartTime after the run (section 9)",
    "B.AssemblyFixtureOnly": "AssemblyFixtureFramework, TestTracking, nothing else (issue #132 today)",
    "C.AssemblyFixturePrototype-sync1": "AssemblyFixtureFramework subclass + prototype decorator, PROBE_SYNC=1, formatter guarded",
    "C.AssemblyFixturePrototype-sync0": "the same, PROBE_SYNC=0 (runner's asynchronous reporting), formatter guarded",
    "C.AssemblyFixturePrototype-sync1-unguarded": "C, PROBE_SYNC=1, formatter exception left to escape the sink",
    "C.AssemblyFixturePrototype-sync0-unguarded": "C, PROBE_SYNC=0, formatter exception left to escape the sink",
    "E.CollectionFixtureOnly": "no TestFramework; DiagrammedTestRun collection fixture writes the report in Dispose (documented fallback)",
    "F.DependencyInjectionPrototype-sync1": "Xunit.DependencyInjection 9.9.2 composed (KronikolDiFramework holds the sealed framework, wraps its executor with the prototype), PROBE_SYNC=1, formatter guarded",
    "F.DependencyInjectionPrototype-sync0": "the same, PROBE_SYNC=0, formatter guarded",
}


def load(path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def runs(lane):
    root = RESULTS / lane
    if not root.is_dir():
        return []
    out = []
    for d in sorted((p for p in root.iterdir() if p.is_dir() and p.name.isdigit()), key=lambda p: int(p.name)):
        out.append({
            "n": int(d.name), "dir": d, "rel": d.relative_to(RESULTS).as_posix(),
            "compare": load(d / "compare.json"), "info": load(d / "run-info.json"), "async": load(d / "asynclocal.json"),
        })
    return out


def secs(v):
    return "-" if v is None else f"{v:.3f}"


def row_for(compare, test):
    """The row of a test by its class-qualified name (from the TRX's test definitions) or by its display name."""
    if not compare:
        return None
    return next((r for r in compare["rows"] if r.get("fqn") == test), None) or next((r for r in compare["rows"] if r["test"] == test), None)


def spec_bytes(run):
    path = run["dir"] / "reports-files.txt"
    if not path.exists():
        return "-"
    for line in path.read_text(encoding="utf-8").splitlines():
        parts = line.split()
        if len(parts) == 2 and parts[1] == "Specifications.html":
            return parts[0]
    return "none"


CRASH = re.compile(r"Unhandled exception|\[FATAL ERROR\]|Catastrophic failure|Test host process crashed|aborted", re.I)


def console_errors(run):
    path = run["dir"] / "console.txt"
    if not path.exists():
        return []
    seen = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if CRASH.search(line) and line not in seen:
            seen.append(line)
    return seen


def cell(r):
    if r is None:
        return "not in the TRX"
    s = r["scenario"]
    if s is None:
        return "**no scenario**"
    return f"{s['result']} as \"{s['name']}\""


lines = []
P = lines.append
P("# XUNIT2_FRAMEWORK_COMPOSITION_PLAN harness: measured results")
P("")
P("Generated by `tools/summarize.py` from the files under `results/` (written by `run.ps1` and `perf.ps1`); each fact names the "
  "file it was read from, relative to `results/`. **Timings are noisy**: other sessions were running test suites on this machine "
  "throughout, so a duration or perf number is indicative, and only a difference far outside the spread of its repeats means anything.")
P("")
P("Versions: xunit 2.9.3; xunit.runner.visualstudio 2.8.2 (one A run on 3.1.5); Microsoft.NET.Test.Sdk 17.14.1; "
  "Xunit.Extensions.AssemblyFixture 2.6.0; Kronikol.xUnit2 4.9.0 built from `src/` at 417c8e58 by ProjectReference; net8.0; "
  "SDK 10.0.300; Windows 11.")
P("")
P("Lanes:")
for lane in LANE_ORDER:
    if runs(lane):
        P(f"- `{lane}`: {LANE_TEXT[lane]} ({len(runs(lane))} run(s))")
P("")


# 0 ------------------------------------------------------------------------------------------------
def theory_cells(c):
    """For rows 1..6: (row whose name the scenario holding the row's call carries, its result, flags) or None."""
    out = {}
    for k in range(1, 7):
        x = next((y for y in c["rows"] if y["path"] and y["path"].startswith(f"/row/{k}/")), None)
        if x is None or x["scenario"] is None:
            out[k] = None
            continue
        m = re.search(r"row: (\d+)", x["scenario"]["name"] or "")
        out[k] = (m.group(1) if m else "none", x["scenario"]["result"], x["flags"])
    return out


def quoted(names):
    return ", ".join('"' + n + '"' for n in names)


def key_facts():
    K = []
    say = K.append
    # A today
    a_runs = [r for lane in ("A.OwnFramework", "A.OwnFramework-runner3.1.5") for r in runs(lane) if r["compare"]]
    if a_runs:
        tests = sorted({len(r["compare"]["rows"]) for r in a_runs})
        scen = sorted({r["compare"]["scenarioCount"] for r in a_runs})
        absent = sum(1 for r in a_runs if all((row_for(r["compare"], t) or {}).get("scenario") is None for t in NEVER_BEFORE))
        disp = [(row_for(r["compare"], DISPLAY[0]) or {}).get("scenario") for r in a_runs]
        say(f"- **A today** ({len(a_runs)} runs: `A.OwnFramework` x{len(runs('A.OwnFramework'))} on runner 2.8.2, "
            f"`A.OwnFramework-runner3.1.5` x{len(runs('A.OwnFramework-runner3.1.5'))}): {'/'.join(map(str, tests))} xUnit tests against "
            f"{'/'.join(map(str, scen))} scenarios. The four tests that never reach Before (skip, constructor, InitializeAsync, class "
            f"fixture) are absent from the report in {absent} of {len(a_runs)} runs. The failing `[Fact(DisplayName)]` is reported "
            f"{', '.join(sorted({d['result'] for d in disp if d}))} in {sum(1 for d in disp if d and d['result'] == 'Passed')} of {len(a_runs)} runs, "
            f"as \"{disp[0]['name'] if disp[0] else '-'}\" with no duration; the passing one and both dotted names are named after their methods "
            f"(`compare.txt` of each run, section 5).")
        perms = []
        for r in a_runs:
            cells = theory_cells(r["compare"])
            wrong_name = sum(1 for k, v in cells.items() if v and v[0] != str(k))
            wrong_result = sum(1 for k, v in cells.items() if v and "RESULT" in v[2])
            moved = sum(1 for k, v in cells.items() if v and "CALL-IN-BACKGROUND" in v[2])
            perm = " ".join(f"{k}>{v[0]}" for k, v in cells.items() if v)
            perms.append(f"{r['rel'].split('/')[0].replace('A.OwnFramework', 'A')} #{r['n']}: {perm} ({wrong_name}/6 under another row's name, "
                         f"{wrong_result}/6 under another verdict, {moved}/6 calls moved to the background section)")
        say("- **A, theory rows** (row whose call it is > row named by the scenario holding that call): " + "; ".join(perms) +
            ". The pairing differs from run to run (section 4). A call is moved to the report's background section as \"Expired\" "
            "when the scenario holding it got another row's end time, earlier than the call.")
        nonser = []
        for r in a_runs:
            wrong = sum(1 for k in range(1, 4)
                        for x in [next((y for y in r["compare"]["rows"] if y["path"] == f"/nonser/{k}"), None)] if x and x["flags"])
            nonser.append(f"{r['rel'].split('/')[0].replace('A.OwnFramework', 'A')} #{r['n']} {wrong}/3")
        say(f"- **A, non-serializable [MemberData] rows** (one test case, three ITests): rows whose scenario disagrees on name, "
            f"duration or call: {', '.join(nonser)}.")
    a2 = [r for r in runs("A2.MethodDisplay") if r["compare"]]
    for r in a2:
        c = r["compare"]
        matched = sum(1 for x in c["rows"] if x["scenario"] and x["scenario"]["seconds"])
        say(f"- **A2, `methodDisplay: method`** (#{r['n']}): scenario results {', '.join(f'{k} {v}' for k, v in sorted(c['scenarioResults'].items()))}; "
            f"{matched} of {c['scenarioCount']} scenarios carry a duration, so no result was matched to a scenario "
            f"({r['rel']}/compare.txt).")
    for r in runs("B.AssemblyFixtureOnly"):
        files = (r["dir"] / "reports-files.txt").read_text(encoding="utf-8").strip() if (r["dir"] / "reports-files.txt").exists() else ""
        say(f"- **B, AssemblyFixtureFramework only** (#{r['n']}): {len((r['compare'] or {}).get('rows', []))} tests in the TRX; "
            f"{'no Reports directory was written' if files.startswith('no Reports') else 'a Reports directory exists'}, and no kronikol-error.log "
            f"({r['rel']}/reports-files.txt). With both TestFramework attributes the build fails with CS0579 (B.AssemblyFixtureOnly/both-attributes-build.txt).")
    # C and F with sync on
    for lane, label in (("C.AssemblyFixturePrototype-sync1", "C, prototype, sync on"), ("F.DependencyInjectionPrototype-sync1", "F, Xunit.DependencyInjection composed, sync on")):
        rs = [r for r in runs(lane) if r["compare"]]
        if not rs:
            continue
        oks = [f"{sum(1 for x in r['compare']['rows'] if not x['flags'])}/{len(r['compare']['rows'])}" for r in rs]
        others = sorted({x["test"] for r in rs for x in r["compare"]["rows"] if x["flags"]})
        never = []
        for t in NEVER_BEFORE:
            got = {cell(row_for(r["compare"], t)) for r in rs}
            never.append(f"{NEVER_BEFORE[t]}: {', '.join(sorted(got))}")
        rows_ok = sum(1 for r in rs for v in theory_cells(r["compare"]).values() if v and not v[2])
        rows_all = sum(1 for r in rs for v in theory_cells(r["compare"]).values() if v)
        ns_ok = sum(1 for r in rs for x in r["compare"]["rows"] if (x["path"] or "").startswith("/nonser/") and not x["flags"])
        ns_all = sum(1 for r in rs for x in r["compare"]["rows"] if (x["path"] or "").startswith("/nonser/"))
        say(f"- **{label}** ({len(rs)} runs): tests agreeing with their scenario on result, name, duration and calls: {', '.join(oks)}. "
            f"Disagreeing: {', '.join(f'`{o}`' for o in others) or 'none'} (the formatter turns \"Order API returns 404 for v1.2\" into \"2\"). "
            f"Never-Before tests: {'; '.join(never)}. Theory rows under their own name, verdict, duration and call: {rows_ok}/{rows_all}; "
            f"non-serializable rows: {ns_ok}/{ns_all} (section 4).")
    for lane in ("C.AssemblyFixturePrototype-sync1", "C.AssemblyFixturePrototype-sync0", "F.DependencyInjectionPrototype-sync1", "F.DependencyInjectionPrototype-sync0"):
        rs = [r for r in runs(lane) if r["async"]]
        if not rs:
            continue
        tot = {k: sum(r["async"]["summary"][k] for r in rs) for k in
               ("beforeEvents", "visibleInBefore", "bodyEvents", "visibleInBody", "resultEvents", "resultSame", "resultNull", "resultOther",
                "beforeOnStartingThread", "trackingIdSeenInBefore", "previousOnFlowNotNull", "tests")}
        no_before = sorted({n for r in rs for n in r["async"]["summary"]["noBefore"]})
        say(f"- **AsyncLocal, `{lane}`** ({len(rs)} runs, {tot['tests']} ITestStarting): the scenario set on ITestStarting is seen in Before "
            f"{tot['visibleInBefore']}/{tot['beforeEvents']}, in the test body {tot['visibleInBody']}/{tot['bodyEvents']}, and on the result message "
            f"{tot['resultSame']}/{tot['resultEvents']} (another test's {tot['resultOther']}, none {tot['resultNull']}); Before ran on the thread "
            f"ITestStarting was delivered on {tot['beforeOnStartingThread']}/{tot['beforeEvents']}; TestTracking's Before ran before PrototypeTracking's "
            f"{tot['trackingIdSeenInBefore']}/{tot['beforeEvents']}; ITestStarting found another test's scenario already on its flow "
            f"{tot['previousOnFlowNotNull']} times. With ITestStarting and a result but no Before: {', '.join(n.replace('Probe.', '') for n in no_before)} "
            f"(`asynclocal.txt` of each run, section 6).")
    for lane in ("C.AssemblyFixturePrototype-sync0", "F.DependencyInjectionPrototype-sync0"):
        rs = [r for r in runs(lane) if r["compare"]]
        if not rs:
            continue
        right = [sum(1 for x in r["compare"]["rows"] if x["scenario"] and not ({"RESULT", "DURATION", "NAME"} & set(x["flags"]))) for r in rs]
        made = [sum(1 for x in r["compare"]["rows"] if x["path"]) for r in rs]
        nowhere = [sum(1 for x in r["compare"]["rows"] if "call-nowhere-in-TestRunReport.json" in x["notes"]) for r in rs]
        agree = ", ".join(str(a) + "/" + str(len(r["compare"]["rows"])) for a, r in zip(right, rs))
        say(f"- **`{lane}`** ({len(rs)} runs): results, durations and names still come from the ITest-keyed match "
            f"(tests whose scenario agrees on all three: {agree}), but no call reaches the report: of the "
            f"{'/'.join(map(str, made))} tests that made a call, the call's path occurs nowhere in TestRunReport.json for "
            f"{'/'.join(map(str, nowhere))} (the calls carry the ids TestTracking's Before made, and no scenario has those; `compare.txt`).")
    for lane in ("C.AssemblyFixturePrototype-sync1-unguarded", "C.AssemblyFixturePrototype-sync0-unguarded"):
        rs = [r for r in runs(lane) if r["compare"]]
        if not rs:
            continue
        parts = []
        for r in rs:
            errs = console_errors(r)
            mark = ("test host crashed, run aborted" if any("Test host process crashed" in e for e in errs)
                    else "Unhandled exception after Finished" if any("Unhandled exception" in e for e in errs)
                    else "[FATAL ERROR] / Catastrophic failure" if any("Catastrophic" in e for e in errs) else "no run-level error")
            parts.append(f"#{r['n']}: TRX {len(r['compare']['rows'])} tests, report {r['compare']['scenarioCount']} scenarios, {mark}")
        say(f"- **`{lane}`** (the formatter's IndexOutOfRangeException on \"Does the thing.\" leaves OnMessage(ITestStarting)): " + "; ".join(parts) +
            ". C's full test set is 21 (section 1, run-level errors).")
    e = [r for r in runs("E.CollectionFixtureOnly") if r["compare"]]
    if e:
        res = sorted({", ".join(f"{k} {v}" for k, v in sorted(r["compare"]["scenarioResults"].items())) for r in e})
        absent = sum(1 for r in e if all((row_for(r["compare"], t) or {}).get("scenario") is None for t in NEVER_BEFORE))
        failed_tests = sorted({sum(1 for x in r["compare"]["rows"] if x["outcome"] == "Failed") for r in e})
        row_names = sorted({x["scenario"]["name"] for r in e for x in r["compare"]["rows"] if (x["path"] or "").startswith("/row/") and x["scenario"]})
        ns_names = sorted({x["scenario"]["name"] for r in e for x in r["compare"]["rows"] if (x["path"] or "").startswith("/nonser/") and x["scenario"]})
        say(f"- **E, collection fixture only** ({len(e)} runs): scenario results {'; '.join(res)} - every scenario Passed with no duration, "
            f"while the TRX has {'/'.join(map(str, failed_tests))} failed tests. The four never-Before tests are absent in {absent} of {len(e)} runs. "
            f"The scenarios holding the six theory rows' calls are named {quoted(row_names)} and those of the three "
            f"non-serializable rows {quoted(ns_names)} (no parameters: nothing renames them). Specifications.html is written in full "
            f"({', '.join(spec_bytes(r) for r in e)} bytes), where a report that saw a failure writes it empty (section 1).")
    # start and end
    if a_runs:
        same = sum(1 for r in a_runs + [r for r in runs("A2.MethodDisplay") + runs("A3.StartTimeProbe") if r["compare"]]
                   if r["compare"]["reportStart"] == r["compare"]["reportEnd"])
        total = len(a_runs) + len([r for r in runs("A2.MethodDisplay") + runs("A3.StartTimeProbe") if r["compare"]])
        say(f"- **Run start and end in A**: the report's start equals its end in {same} of {total} runs of A, A2 and A3 (whole seconds), and "
            f"scenarios ended before that start (section 9).")
    a3 = []
    for r in runs("A3.StartTimeProbe"):
        probe = r["dir"] / "starttime-probe.txt"
        if not probe.exists() or not r["compare"]:
            continue
        values = dict(l.split("=", 1) for l in probe.read_text(encoding="utf-8").split() if "=" in l)
        start = parse_iso(values.get("reportLifecycleStartTimeUtc"))
        first = parse_clock(r["compare"]["trxFirstTestStart"], start)
        last = parse_clock(r["compare"]["trxLastTestEnd"], start)
        if start and first and last:
            a3.append(f"#{r['n']}: {(start - first).total_seconds():.3f}s after the first test started, {(start - last).total_seconds() * 1000:+.0f} ms "
                      f"from the last test's end")
    if a3:
        say("- **ReportLifecycle.StartTime** (A3, read after the run): " + "; ".join(a3) + " (A3.StartTimeProbe/<n>/starttime-probe.txt).")
    di = [r for r in runs("F.DependencyInjectionPrototype-sync1") + runs("F.DependencyInjectionPrototype-sync0") if r["compare"]]
    if di:
        ok = sum(1 for r in di for x in r["compare"]["rows"] if "DiInjected" in (x.get("fqn") or "") and x["outcome"] == "Passed" and x.get("diService"))
        say(f"- **Xunit.DependencyInjection composed** (F): constructor injection worked in {ok} of {len(di)} runs and every run wrote a report "
            f"(section 7b). The composing ITestFramework was enough; the fallback was not needed.")
    f_out = RESULTS / "G.FormatterProbe" / "output.txt"
    if f_out.exists():
        say("- **FormatScenarioDisplayName** (G.FormatterProbe/output.txt): " + "; ".join(
            l.replace("FormatScenarioDisplayName", "").strip().rstrip(".") for l in f_out.read_text(encoding="utf-8").splitlines() if l.strip()) + ".")
    perf = RESULTS / "perf" / "perf.tsv"
    if perf.exists():
        rows = [dict(zip(perf.read_text(encoding="utf-8").splitlines()[0].split("\t"), l.split("\t")))
                for l in perf.read_text(encoding="utf-8").splitlines()[1:] if l.strip()]

        def med(lane, col):
            vals = sorted(float(x[col]) for x in rows if x["lane"] == lane and x.get(col))
            if not vals:
                return "-"
            return f"{statistics.median(vals):.0f}" if col == "report_ms" else f"{statistics.median(vals):.3f}"
        say(f"- **Perf, 2,000 trivial facts** (medians of 5, noisy machine; perf/perf.tsv): xUnit's own assembly time with sync reporting "
            f"{med('C-sync1', 'assembly_s')} s against {med('C-sync0', 'assembly_s')} s without; first-to-last test window "
            f"{med('C-sync1', 'window_s')} / {med('C-sync0', 'window_s')} / A {med('A', 'window_s')} s; wall time of `dotnet test --no-build` "
            f"{med('C-sync1', 'wall_s')} / {med('C-sync0', 'wall_s')} / A {med('A', 'wall_s')} s; report generation {med('C-sync1', 'report_ms')} ms "
            f"with sync, {med('C-sync0', 'report_ms')} ms without (that report has no calls to draw: they were lost, see above).")
    return K


def parse_iso(text):
    if not text:
        return None
    import datetime as dt
    m = re.match(r"^(.*?\.\d{1,6})\d*(Z|[+-]\d\d:\d\d)?$", text.strip())
    text = (m.group(1) + (m.group(2) or "")) if m else text
    return dt.datetime.fromisoformat(text.replace("Z", "+00:00"))


def parse_clock(clock, on):
    """A compare.json clock ("17:53:09.628Z") on the date of `on`."""
    if not clock or not on or clock == "-":
        return None
    import datetime as dt
    h, m, s = clock.rstrip("Z").split(":")
    return on.replace(hour=int(h), minute=int(m), second=int(float(s)), microsecond=int(round((float(s) % 1) * 1_000_000)) % 1_000_000)


P("## Key facts")
P("")
P("Each computed from the run files named in it; sections 1 to 11 below hold every number.")
P("")
for fact in key_facts():
    P(fact)
P("")

# 1 ------------------------------------------------------------------------------------------------
P("## 1. xUnit tests against scenarios, per run")
P("")
P("From each run's `compare.json` (`tools/compare.py`: TRX against TestRunReport.json; a test is matched to the scenario "
  "holding the call it made, or by name when it made none). *ok* = the scenario agrees with the test on result, name, "
  "duration and calls.")
P("")
P("Specifications.html bytes: Kronikol writes Specifications.html and .yml blank (0 bytes) when any scenario failed "
  "(`generateBlankOnFailedTests`), so a non-zero size in a run with failing tests means the report saw none of them "
  "(from `reports-files.txt`).")
P("")
P("| lane / run | exit | xUnit tests | scenarios | report | ok | disagree | no scenario | scenarios with no test | background calls | scenario results in the report | Specifications.html bytes | file |")
P("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
for lane in LANE_ORDER:
    for r in runs(lane):
        c, info = r["compare"], r["info"] or {}
        if not c:
            P(f"| {lane} #{r['n']} | {info.get('exitCode', '-')} | - | - | - | - | - | - | - | - | - | - | {r['rel']}/compare.txt |")
            continue
        rows = c["rows"]
        ok = sum(1 for x in rows if not x["flags"])
        nos = sum(1 for x in rows if "NO-SCENARIO" in x["flags"])
        bad = len(rows) - ok - nos
        P(f"| {lane} #{r['n']} | {info.get('exitCode', '-')} | {len(rows)} | {c['scenarioCount']} | {'yes' if c['reportWritten'] else '**none**'} | "
          f"{ok} | {bad} | {nos} | {len(c['unmatchedScenarios'])} | {len(c['background'])} | "
          f"{', '.join(f'{k} {v}' for k, v in sorted(c.get('scenarioResults', {}).items())) or '-'} | {spec_bytes(r)} | {r['rel']}/compare.json |")
P("")
P("Every run exits 1: six tests fail on purpose. Run-level errors in `console.txt` (the console logger at normal verbosity), and tests "
  "that are in other runs of the same project but missing from this run's TRX:")
P("")
by_project = {}
for lane in LANE_ORDER:
    for r in runs(lane):
        if r["compare"] and r["info"]:
            by_project.setdefault(r["info"]["project"], set()).update(x.get("fqn") or x["test"] for x in r["compare"]["rows"])
quiet = []
for lane in LANE_ORDER:
    for r in runs(lane):
        errors = console_errors(r)
        missing = []
        if r["compare"] and r["info"]:
            have = {x.get("fqn") or x["test"] for x in r["compare"]["rows"]}
            missing = sorted(by_project.get(r["info"]["project"], set()) - have)
        if errors or missing:
            P(f"- {lane} #{r['n']} ({r['rel']}/console.txt): " + ("; ".join(f"`{e[:160]}`" for e in errors[:4]) or "no run-level error")
              + (f"; missing from the TRX: {', '.join(missing)}" if missing else ""))
        else:
            quiet.append(f"{lane} #{r['n']}")
P(f"- no run-level error and no missing test: {', '.join(quiet)}")
P("")

# 2 ------------------------------------------------------------------------------------------------
P("## 2. Every disagreement, test by test")
P("")
P("Flags: RESULT, NAME, DURATION, ERROR-TEXT (the scenario says something else than the test did), FOREIGN-CALLS (it holds "
  "another test's call), CALL-IN-BACKGROUND (the test's call is listed under the report's background calls), NO-SCENARIO.")
for lane in LANE_ORDER:
    for r in runs(lane):
        c = r["compare"]
        if not c:
            continue
        bad = [x for x in c["rows"] if x["flags"]]
        P("")
        P(f"**{lane} #{r['n']}** ({r['rel']}/compare.txt): {len(bad)} of {len(c['rows'])} tests")
        for x in bad:
            s = x["scenario"]
            target = "no scenario" if s is None else (f"\"{s['name']}\" {s['result']} {secs(s['seconds'])}s calls {', '.join(s['calls']) or 'none'}")
            P(f"- `{x['test']}` ({x['outcome']}, {secs(x['seconds'])}s, call {x['path'] or 'none'}) -> {target}: {' '.join(x['flags'])}")
        if c["unmatchedScenarios"]:
            P(f"- scenarios no test maps to: " + "; ".join(f"\"{s['name']}\" {s['result']} calls {', '.join(s['calls']) or 'none'}" for s in c["unmatchedScenarios"]))
P("")

# 3 ------------------------------------------------------------------------------------------------
P("## 3. Tests that never reach Before (skip, constructor, InitializeAsync, class fixture)")
P("")
P("What the report says for each (from `compare.json`; *no scenario* = absent from the report).")
P("")
P("| lane / run | " + " | ".join(NEVER_BEFORE.values()) + " |")
P("|---|" + "---|" * len(NEVER_BEFORE))
for lane in LANE_ORDER:
    for r in runs(lane):
        if r["compare"]:
            P(f"| {lane} #{r['n']} | " + " | ".join(cell(row_for(r["compare"], t)) for t in NEVER_BEFORE) + " |")
P("")
P("In the TRX all four are reported: Skipped as NotExecuted and the other three as Failed (every `compare.txt`).")
P("")

# 4 ------------------------------------------------------------------------------------------------
P("## 4. Theory rows: which scenario holds each row's call")
P("")
P("Each `[InlineData(row, ms)]` row GETs `/row/{row}/slept/{ms}`, sleeps `ms`, and row 4 fails. A cell reads: the scenario "
  "holding that row's call (or, flagged CALL-MISSING, the scenario with the row's names when no scenario holds it), its result "
  "and duration, and the flags of section 2 when it disagrees with the row's own TRX result.")
P("")
for lane in LANE_ORDER:
    rs = [r for r in runs(lane) if r["compare"]]
    if not rs:
        continue
    P(f"**{lane}**")
    P("")
    P("| run | " + " | ".join(f"row {k}" for k in range(1, 7)) + " |")
    P("|---|" + "---|" * 6)
    for r in rs:
        cells = []
        for k in range(1, 7):
            x = next((y for y in r["compare"]["rows"] if y["path"] and y["path"].startswith(f"/row/{k}/")), None)
            if x is None:
                cells.append("not in the TRX")
            elif x["scenario"] is None:
                cells.append("no scenario")
            else:
                s = x["scenario"]
                mark = f" ({' '.join(x['flags'])})" if x["flags"] else ""
                cells.append(f"\"{s['name']}\" {s['result']} {secs(s['seconds'])}s{mark}")
        P(f"| #{r['n']} | " + " | ".join(cells) + " |")
    P("")
    nonser = []
    for r in rs:
        parts = []
        for k in range(1, 4):
            x = next((y for y in r["compare"]["rows"] if y["path"] == f"/nonser/{k}"), None)
            if x is None:
                parts.append(f"/nonser/{k}: not run")
            elif x["scenario"] is None:
                parts.append(f"/nonser/{k}: no scenario" + (" (call in background)" if any(b["path"] == f"/nonser/{k}" for b in r["compare"]["background"]) else ""))
            else:
                parts.append(f"/nonser/{k} in \"{x['scenario']['name']}\"{' x' if x['flags'] else ''}")
        nonser.append(f"#{r['n']}: " + "; ".join(parts))
    P("Non-serializable [MemberData] rows: " + " | ".join(nonser))
    P("")

# 5 ------------------------------------------------------------------------------------------------
P("## 5. [Fact(DisplayName = ...)]")
P("")
P("| lane / run | " + " | ".join(f"\"{d}\" (TRX)" for d in DISPLAY + DOTS) + " |")
P("|---|" + "---|" * (len(DISPLAY) + len(DOTS)))
for lane in LANE_ORDER:
    for r in runs(lane):
        if not r["compare"]:
            continue
        cells = []
        for d in DISPLAY + DOTS:
            x = row_for(r["compare"], d)
            if x is None:
                # methodDisplay=method keeps a DisplayName as written, so the name is the same; absent means not run
                cells.append("not in the TRX")
            else:
                cells.append(f"TRX {x['outcome']}; report {cell(x)}")
        P(f"| {lane} #{r['n']} | " + " | ".join(cells) + " |")
P("")
P("Formatter exceptions and report-generation failures, per run (files copied from the test output directory):")
P("")
for lane in LANE_ORDER:
    for r in runs(lane):
        found = []
        for f in ("prototype-formatter.log.txt", "prototype-error.log.txt", "kronikol-error.log.txt"):
            p = r["dir"] / f
            if p.exists():
                first = p.read_text(encoding="utf-8", errors="replace").strip().splitlines()
                found.append(f"`{f}`: {len(first)} line(s), first: {first[0][:220] if first else '(empty)'}")
        if found:
            P(f"- {lane} #{r['n']}: " + "; ".join(found))
P("- every other run: none of the three files was written")
P("")

# 6 ------------------------------------------------------------------------------------------------
P("## 6. AsyncLocal set in OnMessage(ITestStarting): where it is visible (C)")
P("")
P("From each C run's `asynclocal.json` (`tools/asynclocal.py` over the prototype's `asynclocal.tsv`). Before, body and result "
  "count the tests that reached that point; *same thread* = delivered on the thread that delivered ITestStarting.")
P("")
P("| lane / run | sync option seen by the executor | tests | Before sees it | body sees it | result message sees it (same/none/other) | Before on ITestStarting thread | result on ITestStarting thread | TestTracking ran before PrototypeTracking | ITestStarting found a scenario already on the flow | Before after ITestStarting (us, median / max) | tests with no Before |")
P("|---|---|---|---|---|---|---|---|---|---|---|---|")
for lane in LANE_ORDER:
    for r in runs(lane):
        a = r["async"]
        if not a:
            continue
        s = a["summary"]
        us = s["beforeMicrosAfterStarting"]
        timing = f"{us[len(us) // 2]} / {us[-1]}" if us else "-"
        P(f"| {lane} #{r['n']} | {'; '.join(s['options'])} | {s['tests']} | {s['visibleInBefore']}/{s['beforeEvents']} | {s['visibleInBody']}/{s['bodyEvents']} | "
          f"{s['resultSame']}/{s['resultNull']}/{s['resultOther']} of {s['resultEvents']} | {s['beforeOnStartingThread']}/{s['beforeEvents']} | "
          f"{s['resultOnStartingThread']}/{s['resultEvents']} | {s['trackingIdSeenInBefore']}/{s['beforeEvents']} | {s['previousOnFlowNotNull']} | {timing} | "
          f"{len(s['noBefore'])}: {', '.join(n.replace('Probe.', '') for n in s['noBefore'])} |")
P("")
P("Per-test rows (threads, visibility, Before attributes in the order xUnit reported them): each C run's `asynclocal.txt`.")
P("")

# 7 ------------------------------------------------------------------------------------------------
P("## 7. Assembly fixture (IAssemblyFixture<SharedThing>)")
P("")
for lane in LANE_ORDER:
    for r in runs(lane):
        c = r["compare"]
        if not c:
            continue
        users = [x for x in c["rows"] if "AssemblyFixtureUser" in x["test"]]
        if not users:
            continue
        ids = {tuple(x["sharedThing"])[0] for x in users if x["sharedThing"]}
        created = {tuple(x["sharedThing"])[1] for x in users if x["sharedThing"]}
        P(f"- {lane} #{r['n']}: " + ", ".join(f"{x['test'].split('.')[1]} {x['outcome']}" for x in users) +
          f"; fixture instances seen {len(ids)}, constructor count reported {', '.join(sorted(created)) or '-'} ({r['rel']}/compare.txt)")
P("")

P("## 7b. Xunit.DependencyInjection (F): constructor injection through the composing framework")
P("")
for lane in LANE_ORDER:
    for r in runs(lane):
        c = r["compare"]
        if not c:
            continue
        users = [x for x in c["rows"] if "DiInjected" in (x.get("fqn") or "")]
        if not users:
            continue
        for x in users:
            s = x["scenario"]
            service = x.get("diService")
            injected = f'instance {service[0]} said "{service[1].strip()}"' if service else "**not seen**"
            where = f'"{s["name"]}" {s["result"]} calls {", ".join(s["calls"]) or "none"}' if s else "no scenario"
            P(f"- {lane} #{r['n']}: `{x['test']}` {x['outcome']}; injected service {injected}; report: {where}; "
              f"report written: {'yes' if c['reportWritten'] else 'no'} ({r['rel']}/compare.txt)")
P("")

# 8 ------------------------------------------------------------------------------------------------
P("## 8. Issue #132 today (B): is any report written, and both TestFramework attributes")
P("")
for r in runs("B.AssemblyFixtureOnly"):
    files = (r["dir"] / "reports-files.txt").read_text(encoding="utf-8").strip() if (r["dir"] / "reports-files.txt").exists() else "-"
    errors = [f for f in ("kronikol-error.log.txt",) if (r["dir"] / f).exists()]
    P(f"- B #{r['n']}: exit {(r['info'] or {}).get('exitCode')}; report directory: {files.splitlines()[0] if files else '-'}; "
      f"kronikol-error.log: {'yes' if errors else 'no'} ({r['rel']}/reports-files.txt)")
both = RESULTS / "B.AssemblyFixtureOnly" / "both-attributes-build.txt"
if both.exists():
    P("- Both `[assembly: TestFramework]` attributes in one assembly (scratch copy of B, `B.AssemblyFixtureOnly/both-attributes-build.txt`):")
    P("")
    P("```")
    for line in both.read_text(encoding="utf-8").splitlines():
        if line.startswith("exit code") or "error" in line:
            P(line.strip())
    P("```")
P("")

# 9 ------------------------------------------------------------------------------------------------
P("## 9. The report's run start and end")
P("")
P("Report times from TestRunReport.json (whole seconds, UTC); TRX run times and first test start / last test end (UTC). "
  "A sets no `ReportLifecycle.Options`, so nothing touches `ReportLifecycle` before `GenerateReports()` at the end of the run.")
P("")
P("| lane / run | report start | report end | TRX run start | TRX first test start | TRX last test end | TRX finish | earliest scenario endedAt | file |")
P("|---|---|---|---|---|---|---|---|---|")
for lane in LANE_ORDER:
    for r in runs(lane):
        c = r["compare"]
        if not c:
            continue
        text = (r["dir"] / "compare.txt").read_text(encoding="utf-8")
        tests = re.search(r"TRX tests:\s+first start (\S+)\s+last end (\S+)", text)
        P(f"| {lane} #{r['n']} | {c['reportStart'] or '-'} | {c['reportEnd'] or '-'} | {c['trxStart']} | {tests.group(1) if tests else '-'} | "
          f"{tests.group(2) if tests else '-'} | {c['trxFinish']} | {c['earliestEndedAt'] or '-'} | {r['rel']}/compare.txt |")
P("")

P("ReportLifecycle.StartTime itself (A3: read by reflection in a ProcessExit handler once the run is over; "
  "`moduleFirstUsedUtc` is when the first test touched the test assembly's code):")
P("")
for r in runs("A3.StartTimeProbe"):
    probe = r["dir"] / "starttime-probe.txt"
    values = dict(l.split("=", 1) for l in probe.read_text(encoding="utf-8").split() if "=" in l) if probe.exists() else {}
    c = r["compare"] or {}
    if values:
        P(f"- A3 #{r['n']}: StartTime {values.get('reportLifecycleStartTimeUtc')}; module first used {values.get('moduleFirstUsedUtc')}; "
          f"TRX first test start {c.get('trxFirstTestStart')}, last test end {c.get('trxLastTestEnd')}; process exit {values.get('processExitUtc')}; "
          f"report start/end {c.get('reportStart')} / {c.get('reportEnd')} ({r['rel']}/starttime-probe.txt)")
    else:
        P(f"- A3 #{r['n']}: no starttime-probe.txt ({r['rel']})")
P("")

# 10 -----------------------------------------------------------------------------------------------
P("## 10. FormatScenarioDisplayName called directly (G)")
P("")
f_out = RESULTS / "G.FormatterProbe" / "output.txt"
if f_out.exists():
    P("`G.FormatterProbe/output.txt`:")
    P("")
    P("```")
    P(f_out.read_text(encoding="utf-8").strip())
    P("```")
P("")

# 11 -----------------------------------------------------------------------------------------------
P("## 11. Perf: 2,000 trivial facts")
P("")
perf = RESULTS / "perf" / "perf.tsv"
if perf.exists():
    rows = [dict(zip(perf.read_text(encoding="utf-8").splitlines()[0].split("\t"), l.split("\t")))
            for l in perf.read_text(encoding="utf-8").splitlines()[1:] if l.strip()]
    P("From `perf/perf.tsv` (columns explained in `tools/perf_row.py`). Median [min - max] over the runs of each lane, seconds "
      "(report_ms in milliseconds). C = the prototype framework (AssemblyFixtureFramework + decorator); A = Kronikol's ReportingTestFramework.")
    P("")
    cols = ["wall_s", "xunit_s", "vstest_total_s", "window_s", "assembly_s", "report_ms"]
    P("| lane | runs | passed / total | " + " | ".join(cols) + " |")
    P("|---|---|---|" + "---|" * len(cols))
    for lane in ("C-sync1", "C-sync0", "A"):
        lr = [x for x in rows if x["lane"] == lane]
        if not lr:
            continue
        cells = []
        for col in cols:
            vals = sorted(float(x[col]) for x in lr if x.get(col))
            cells.append(f"{statistics.median(vals):.3f} [{vals[0]:.3f} - {vals[-1]:.3f}]" if vals else "-")
        passed = ", ".join(sorted({f"{x['passed']}/{x['total']}" for x in lr}))
        P(f"| {lane} | {len(lr)} | {passed} | " + " | ".join(cells) + " |")
    P("")
    P("Per run, in the order taken:")
    P("")
    P("```")
    P(perf.read_text(encoding="utf-8").strip())
    P("```")
else:
    P("Not run yet (`perf.ps1`).")
P("")

(RESULTS / "SUMMARY.md").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
print(f"wrote {RESULTS / 'SUMMARY.md'} ({len(lines)} lines)")
