using Kronikol.Sql;

namespace Kronikol.Tests;

/// <summary>
/// SQL is classified by regular expression, and two of the table extractors — the one after
/// <c>FROM</c> and the one after <c>INTO</c> — are unanchored: they take the first match anywhere in the
/// command text. Without a lexer that means a comment or a string literal beats the real clause.
/// <para>
/// This is not hypothetical. A user's component diagram listed <c>SELECT FROM the</c> as one of its
/// ClickHouse operations, next to twenty-eight real table names: the query carried a comment such as
/// <c>-- rolled up from the weekly aggregate</c>, and "the" was captured as the table. Besides being
/// wrong on the face of it, every distinct artefact of this kind is another operation in the
/// architecture overview's edge label, which is what made that label long enough to overflow the canvas.
/// </para>
/// <para>
/// The other half of the same defect is at the front of the statement: the keyword matcher and all three
/// prefix strippers are <c>^</c>-anchored, so a statement that <em>opens</em> with a comment used to
/// classify as <c>Other</c> with no table at all — and at <c>Summarised</c> verbosity a call classified
/// that way is dropped from the report entirely.
/// </para>
/// </summary>
public class UnifiedSqlCommentStrippingTests
{
    // ─── The reported artefact: a comment before the real FROM ──

    [Fact]
    public void A_line_comment_mentioning_from_does_not_become_the_table()
    {
        var result = UnifiedSqlClassifier.Classify(
            "SELECT store_id, revenue -- rolled up from the weekly aggregate\nFROM location_performance_weekly WHERE dt >= @start");

        Assert.Equal(UnifiedSqlOperation.Select, result.Operation);
        Assert.Equal("location_performance_weekly", result.TableName);
    }

    [Fact]
    public void A_block_comment_mentioning_from_does_not_become_the_table()
    {
        var result = UnifiedSqlClassifier.Classify(
            "SELECT * /* read from the archive */ FROM location_performance_weekly");

        Assert.Equal(UnifiedSqlOperation.Select, result.Operation);
        Assert.Equal("location_performance_weekly", result.TableName);
    }

    [Fact]
    public void A_string_literal_mentioning_from_does_not_become_the_table()
    {
        var result = UnifiedSqlClassifier.Classify(
            "SELECT 'copied from the legacy system' AS note FROM location_performance_weekly");

        Assert.Equal(UnifiedSqlOperation.Select, result.Operation);
        Assert.Equal("location_performance_weekly", result.TableName);
    }

    [Fact]
    public void A_comment_mentioning_into_does_not_become_the_insert_target()
    {
        var result = UnifiedSqlClassifier.Classify(
            "INSERT /* copy into the staging area */ INTO location_performance_weekly SELECT * FROM raw");

        Assert.Equal(UnifiedSqlOperation.Insert, result.Operation);
        Assert.Equal("location_performance_weekly", result.TableName);
    }

    // ─── A statement that opens with a comment ──────────────────

    [Fact]
    public void A_leading_line_comment_does_not_defeat_classification()
    {
        var result = UnifiedSqlClassifier.Classify(
            "-- pull from the weekly rollup\nSELECT * FROM location_performance_weekly");

        Assert.Equal(UnifiedSqlOperation.Select, result.Operation);
        Assert.Equal("location_performance_weekly", result.TableName);
    }

    [Fact]
    public void A_leading_block_comment_does_not_defeat_classification()
    {
        var result = UnifiedSqlClassifier.Classify(
            "/* generated by the reporting layer */ UPDATE location_performance_weekly SET revenue = 0");

        Assert.Equal(UnifiedSqlOperation.Update, result.Operation);
        Assert.Equal("location_performance_weekly", result.TableName);
    }

    [Fact]
    public void A_leading_comment_does_not_defeat_the_prefix_strippers()
    {
        var setPrefixed = UnifiedSqlClassifier.Classify(
            "-- reporting\nSET NOCOUNT ON;\nSELECT * FROM Users");
        Assert.Equal(UnifiedSqlOperation.Select, setPrefixed.Operation);
        Assert.Equal("Users", setPrefixed.TableName);

        var ctePrefixed = UnifiedSqlClassifier.Classify(
            "/* rollup */ WITH cte AS (SELECT 1) SELECT * FROM cte");
        Assert.Equal(UnifiedSqlOperation.Select, ctePrefixed.Operation);
    }

    // ─── Not a comment, and not a string ────────────────────────

    [Fact]
    public void Two_dashes_inside_a_string_literal_are_not_a_comment()
    {
        // Stripping has to read strings and comments in one pass, or a `--` inside a literal swallows
        // the rest of the line — including the real FROM clause.
        var result = UnifiedSqlClassifier.Classify(
            "SELECT * FROM location_performance_weekly WHERE note = 'a -- b'");

        Assert.Equal(UnifiedSqlOperation.Select, result.Operation);
        Assert.Equal("location_performance_weekly", result.TableName);
    }

    [Fact]
    public void A_doubled_quote_inside_a_string_literal_does_not_end_it()
    {
        var result = UnifiedSqlClassifier.Classify(
            "SELECT * FROM location_performance_weekly WHERE note = 'it''s from the archive'");

        Assert.Equal(UnifiedSqlOperation.Select, result.Operation);
        Assert.Equal("location_performance_weekly", result.TableName);
    }

    [Fact]
    public void A_quoted_identifier_is_still_a_table_name()
    {
        // Double quotes, brackets and backticks delimit identifiers, not strings — the extractors depend
        // on reading through them, so stripping must leave them alone.
        Assert.Equal("Users", UnifiedSqlClassifier.Classify("SELECT * FROM \"Users\"").TableName);
        Assert.Equal("Users", UnifiedSqlClassifier.Classify("SELECT * FROM [Users]").TableName);
        Assert.Equal("Users", UnifiedSqlClassifier.Classify("SELECT * FROM `Users`").TableName);
    }

    [Fact]
    public void A_minus_that_is_not_a_comment_is_left_alone()
    {
        var result = UnifiedSqlClassifier.Classify("SELECT a-b AS d FROM Users");

        Assert.Equal(UnifiedSqlOperation.Select, result.Operation);
        Assert.Equal("Users", result.TableName);
    }

    [Fact]
    public void An_unterminated_block_comment_swallows_the_rest_and_still_classifies()
    {
        // Malformed input must not throw or hang; the keyword before it is still readable.
        var result = UnifiedSqlClassifier.Classify("SELECT * FROM Users /* unterminated");

        Assert.Equal(UnifiedSqlOperation.Select, result.Operation);
        Assert.Equal("Users", result.TableName);
    }

    [Fact]
    public void An_unterminated_string_swallows_the_rest_and_still_classifies()
    {
        var result = UnifiedSqlClassifier.Classify("SELECT * FROM Users WHERE n = 'unterminated");

        Assert.Equal(UnifiedSqlOperation.Select, result.Operation);
        Assert.Equal("Users", result.TableName);
    }

    // ─── The command text itself is untouched ───────────────────

    [Fact]
    public void The_original_command_text_is_returned_verbatim()
    {
        // Stripping is a classification aid only. What the report shows is the SQL that ran, comments
        // and all.
        const string sql = "SELECT * /* read from the archive */ FROM Users -- and its comment";

        Assert.Equal(sql, UnifiedSqlClassifier.Classify(sql).CommandText);
    }
}
